backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - member
# publish_mode: editorial_workflow
media_folder: "/assets/uploads/"
logo_url: "/assets/img/logos/Logo-CMS.png"

collections:
  - label: "Prepartory"
    name: "prepartory"
    folder: "_data/prepartory/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation", "Engineering Mathematics 1","Engineering Physics 1","Mechanics 1","Engineering Chemistry", "Computer Technology", "Engineering Drawing and Projection", "Production Technology", "Technical English", "Engineering History"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}
  - label: "Electrical - Year 1"
    name: "electricalyear1"
    folder: "_data/electrical/year1/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation", "Engineering Mathematics 2","Engineering Physics 2","Electrical Circuits","Logical Circuits", "Data Structures and Algorithms", "Civil Engineering", "Mechanical Power Engineering", "Computer programming", "Electrical Measurements and Instruments", "Technical Reports Writing"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}
  - label: "Electrical - Year 2"
    name: "electricalyear2"
    folder: "_data/electrical/year2/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation", "Engineering Mathematics 3","Automatic Control Systems","Electromagnetic Fields","Electronic Engineering", "Industrial Safety", "Microprocessor Systems", "Database Management Systems", "Energy Conversion", "Signal Processing","Engineering Economics","Electrical and Electronic Tests","Systems Dynamics and Control Components"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}
  - label: "Electrical - Year 3 Computer"
    name: "electricalyear3computer"
    folder: "_data/electrical/year3computer/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation","Computer Architecture","Design and Analysis of Algorithms", "Multimedia", "Automatic Control Systems 2", "Projects Management and Marketing", "Engineering Mathematics 4", "Compilers", "Software Engineering", "Modeling and Simulation", "Operating Systems", "Digital Communications","Digital Control"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}
  - label: "Electrical - Year 3 Power"
    name: "electricalyear3power"
    folder: "_data/electrical/year3power/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation", "Electrical Tests 2", "Electrical Machines 1", "High Voltage Engineering","Power Electronics", "Automatic Control", "Project Management and Marketing", "Engineering Mathematics 4", "Electrical Machines 2", "Transmission and Distribution", "Electrical Power Systems Analysis 1", "Data Communication Systems"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}
  - label: "Electrical - Year 3 Telecom"
    name: "electricalyear3telecom"
    folder: "_data/electrical/year3telecom/"
    create: false
    slug: "{{slug}}"
    extension: "yml"
    editor:
      preview: false
    fields: # The fields for each document, usually in front matter.
      - {name: "title", label: "Collection Title:", widget: "string", hint: "Fall is Term 1, Winter is Term 2"}
      - label: "Files"
        name: "files"
        widget: "list"
        fields: 
        - {name: "publishdate", label: "File Publish Date", widget: "datetime", format: "YYYY/MM/DD"}
        - {name: "subject", label: "File Subject", widget: "select", options: ["Week Compilation", "Communication Systems 1", "Electronic Tests and Measurements 1", "Electronic Devices","Microprocessors and their Applications", "Electromagnetic radiation", "Engineering Mathematics 4", "Optoelectronics", "Electronic Circuits 2", "Project Management and Marketing"]}
        - {name: "type", label: "File Type", widget: "select", options: ["Lecture","Section","Book","Exercise"]}
        - {name: "url", label: "File URL", widget: "string", hint: "Google Drive link to the file."}
        - {name: "description", label: "File Description (optional)", widget: "string", required: "false",  hint: "Ex. Introduction into fluids, Signal Types, etc...."}