backend:
  name: git-gateway
  branch: master
  accept_roles: #optional - accepts all users if left out
    - admin
    - member

# publish_mode: editorial_workflow

media_folder: "/assets/uploads/"
logo_url: "/assets/img/logos/Logo-CMS.png"

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "article" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
     preview: false
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Type", name: "type", widget: "select", options: ["left", "center", "right"]}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Files"
        name: "files"
        widget: "list"
        field: {name: tag, label: Tag, widget: string}   